server:
  port: 8081


#druid:
#  url:  jdbc:sqlserver://192.168.3.99:1433;DatabaseName=TopDB
#  driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
#  username:  sa
#  password:  top@qadb123
#  initial-size:  10
#  max-active:  50
#  min-idle:  10
#  max-wait:  60000
#  pool-prepared-statements:  true
#  max-pool-prepared-statement-per-connection-size:  20
#  validation-query:  SELECT 1
#  test-on-borrow:  false
#  test-on-return:  false
#  test-while-idle:  true
#  time-between-eviction-runs-millis:  60000
#  filters:  stat,wall

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.cgo.login_module
  application:
    name: cgo_login
  consumer:
    timeout: 10000
  provider:
    timeout: 10000
key:
  keyFileName: cgo.keystore
  pwd: cgopwd
  storePwd: cgostorepwd
  alias: cgo