spring:
  profiles:
    active: db

# 配置日志打印 级别
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    root: info

server:
  port: 8082

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.cgo.mobile
  application:
    name: cgo_web
  consumer:
    timeout: 10000
  provider:
    timeout: 10000
